### ISSUE TITLE
Error in the example

### ISSUE THREAD

**Issue by AmenRa** [words/gunning-fog#7]
Hi, I noticed an error in the example under "Usage" section.
You wrote:

> /\* For “The Australian platypus is seemingly a hybrid of
> - a mammal and reptilian creature.” (1 sentence; 13 words;
> - 26 syllables; 4 polysillabic words, 2 of which jargon/proper
> - nouns). */

`
gunningFog({
  sentence: 1,
  word: 13,
  complexPolysillabicWord: 2
});
`

The complex polysyllabic words are 4 and not 2, I counted the syllables with your node module "syllables", with "nlp-compromise"/"nlp-syllables" and online here: [http://gunning-fog-index.com/](url).

Minor error: polysYllabic, not polysillabic. (I'm trying to help not to be offensive)

Thank you for all you work to bring nlp-related things in JS!

**Comment by wooorm** [comment]
Thanks for pointing this out, @AmenRa666!

Would you be interested in creating a PR?

If so, after cloning, and making the changes, do `npm install` and `npm test`, which will check code-style, run tests, and whatnot. Thanks again!

**Comment by AmenRa** [comment]
Yeah, I think I can do it.
Tomorrow I'll try. (I'm kinda new with Git)

**Comment by wooorm** [comment]
Cool, let me know if it works out, or not, or if I can help :)

**Comment by wooorm** [comment]
@AmenRa666 Ping!
